# Builds widgets/shared/mii-body.js from the Mii body and default head in models/Mii (Default)/.
# Run from the repository root:  python tools/mii-body-build.py
# Needs Pillow (pip install pillow).
#
# Output: window.MII_MODEL = { body: {shirt, pants, shoes}, head: {...}, tex: {...} }
# Each part: pos (Float32 base64, x y z), nrm (Float32 base64, smooth normals), uv (Float32 base64),
# idx (Uint16 base64). Units are the units of the renderer's 3D heads (the OBJ files are scaled by 10).
import base64, io, json, math, os, struct, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'models', 'Mii (Default)')
OUT = os.path.join(ROOT, 'widgets', 'shared', 'mii-body.js')
SCALE = 10


def read_obj(name):
    V, T, parts, cur = [], [], {}, None
    with open(os.path.join(SRC, name)) as f:
        for line in f:
            p = line.split()
            if not p:
                continue
            if p[0] == 'o':
                cur = p[1]
                parts[cur] = []
            elif p[0] == 'v':
                V.append([float(x) * SCALE for x in p[1:4]])
            elif p[0] == 'vt':
                T.append([float(x) for x in p[1:3]])
            elif p[0] == 'f':
                parts[cur].append([tuple(int(x) - 1 for x in t.split('/')[:2]) for t in p[1:]])
    return V, T, parts


def pack(fmt, values):
    return base64.b64encode(struct.pack('<%d%s' % (len(values), fmt), *values)).decode()


def part(V, T, faces):
    keys, index, idx = [], {}, []
    for f in faces:
        tri = []
        for vt in f:
            if vt not in index:
                index[vt] = len(keys)
                keys.append(vt)
            tri.append(index[vt])
        for i in range(1, len(tri) - 1):
            idx += [tri[0], tri[i], tri[i + 1]]
    pos = [V[v] for v, t in keys]
    # Smooth normals, shared by vertices at the same place (the OBJ splits them at UV seams).
    acc = {}
    for i in range(0, len(idx), 3):
        a, b, c = (pos[idx[i]], pos[idx[i + 1]], pos[idx[i + 2]])
        u = [b[k] - a[k] for k in range(3)]
        w = [c[k] - a[k] for k in range(3)]
        n = [u[1] * w[2] - u[2] * w[1], u[2] * w[0] - u[0] * w[2], u[0] * w[1] - u[1] * w[0]]
        for j in idx[i:i + 3]:
            key = tuple(round(x, 2) for x in pos[j])
            s = acc.setdefault(key, [0, 0, 0])
            for k in range(3):
                s[k] += n[k]
    nrm = []
    for p in pos:
        n = acc.get(tuple(round(x, 2) for x in p), [0, 1, 0])
        l = math.sqrt(sum(x * x for x in n)) or 1
        nrm += [x / l for x in n]
    uv = []
    for v, t in keys:
        uv += T[t] if t >= 0 else [0, 0]
    return {
        'pos': pack('f', [x for p in pos for x in p]),
        'nrm': pack('f', nrm),
        'uv': pack('f', uv),
        'idx': pack('H', idx),
    }


def png(img, mode):
    img = img.convert(mode)
    buf = io.BytesIO()
    img.save(buf, 'PNG', optimize=True)
    return 'data:image/png;base64,' + base64.b64encode(buf.getvalue()).decode()


def tex(name):
    return Image.open(os.path.join(SRC, name + '.png'))


V, T, P = read_obj('default.obj')
body = {
    'shirt': part(V, T, P['name.002_name.008']),
    'pants': part(V, T, P['name_name.006']),
    'shoes': part(V, T, P['name.003_name.011']),
}
V, T, P = read_obj('def_m.obj')
head = {
    'faceline': part(V, T, P['name.002']),
    'nose': part(V, T, P['name.004']),
    'hair': part(V, T, P['name.001']),
    'mask': part(V, T, P['name']),
    'noseline': part(V, T, P['name.003']),
}

# Shirt: red = shading (albedo), green = where the skin shows (hands, neck). Pants and shoes: shading.
alb = tex('shirt_alb').convert('L')
msk = tex('shirt_msk').convert('RGB').split()[1]
shirt = Image.merge('RGB', (alb, msk, Image.new('L', alb.size, 0)))
textures = {
    'shirt': png(shirt, 'RGB'),
    'pants': png(tex('pants_alb'), 'L'),
    'shoes': png(tex('shoe_alb'), 'L'),
    'face': png(tex('msk_m'), 'RGBA'),
    'noseline': png(tex('msk_n'), 'RGBA'),
}

data = {'body': body, 'head': head, 'tex': textures, 'skin': '#ffd3ad', 'hair': '#442211'}
with open(OUT, 'w', newline='\n') as f:
    f.write('// Generated by tools/mii-body-build.py from models/Mii (Default)/ (Mii body and default head,\n')
    f.write('// ripped by Centrixe at The Models Resource). Do not edit by hand.\n')
    f.write('window.MII_MODEL = ' + json.dumps(data, separators=(',', ':')) + ';\n')
print('wrote', OUT, os.path.getsize(OUT), 'bytes')
